version: '3'

services:
  odoo17-elerning:
    container_name: odoo17-elerning
    image: odoo:17
    # depends_on:
    #   - postgres
    ports:
      - "18469:8069"
      - "18472:8072" # live chat
    tty: true
    command: --
    environment:
      # - HOST=localhost
      # - USER=odoo
      # - PASSWORD=odoo17@2024

      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo17@2024
      - POSTGRES_DB=postgres
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./odoo-addons:/mnt/extra-addons
      # - ./core/enterprise:/mnt/enterprise:ro
      - ./odoo-config/odoo-elerning.conf:/etc/odoo/odoo.conf
      - ./odoo-log/odoo17-elerning.log:/var/log/odoo/odoo-server.log
      - ./odoo-data:/var/lib/odoo
    restart: always     
    networks:
      - odoo-network        # run as a service

  odoo17-project:
    container_name: odoo17-project
    image: odoo:17
    # depends_on:
    #   - postgres
    ports:
      - "18369:8069"
      - "18372:8072" # live chat
    tty: true
    command: --
    environment:
      # - HOST=localhost
      # - USER=odoo
      # - PASSWORD=odoo17@2024

      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo17@2024
      - POSTGRES_DB=postgres
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./odoo-addons:/mnt/extra-addons
      - ./core/enterprise:/mnt/enterprise:ro
      - ./odoo-config/odoo-project.conf:/etc/odoo/odoo.conf
      - ./odoo-log/odoo17-project.log:/var/log/odoo/odoo-server.log
      - ./odoo-data:/var/lib/odoo
    restart: always     
    networks:
      - odoo-network        # run as a service

  odoo17-demo:
    container_name: odoo17-demo
    image: odoo:17
    # depends_on:
    #   - postgres
    ports:
      - "18269:8069"
      - "18272:8072" # live chat
    tty: true
    command: --
    environment:
      # - HOST=localhost
      # - USER=odoo
      # - PASSWORD=odoo17@2024

      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo17@2024
      - POSTGRES_DB=postgres
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./odoo-addons:/mnt/extra-addons
      - ./odoo-config/odoo-demo.conf:/etc/odoo/odoo.conf
      - ./odoo-log:/var/log/odoo
      - ./odoo-data:/var/lib/odoo
    restart: always     
    networks:
      - odoo-network        # run as a service

  odoo17:
    container_name: odoo17-web
    image: odoo:17
    # depends_on:
    #   - postgres
    ports:
      - "18169:8069"
      - "18172:8072" # live chat
    tty: true
    command: --
    environment:
      # - HOST=localhost
      # - USER=odoo
      # - PASSWORD=odoo17@2024

      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo17@2024
      - POSTGRES_DB=postgres
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./odoo-addons:/mnt/extra-addons
      - ./odoo-config:/etc/odoo
      - ./odoo-log:/var/log/odoo
      - ./odoo-data:/var/lib/odoo
    restart: always     
    networks:
      - odoo-network        # run as a service
    
  # frontend:
  #   build:
  #     context: ./next-app
  #   container_name: odoo17-app
  #   working_dir: /app
  #   # Set environment variables based on the .env file
  #   env_file:
  #     - .env
  #   volumes:
  #     # - ./next-app:/app
  #     - ./next-app/app:/app/app
  #     - ./next-app/public:/app/public
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   # command: npm start
  #   networks:
  #     - odoo-network

volumes:
  odoo-addons:
  odoo-config:
  odoo-data:
  odoo-log:

networks:
  odoo-network:
    driver: bridge